### ISSUE TITLE
Add command line flags

### ISSUE THREAD

**Issue by tommywei-cpu** [13thsymphony/HDRImageViewer#28]
@13thsymphony  is a very nice tool. Just wondering is it possible to make the software into an .exe file, so that I can call it in cmd, and with “-f” to specify a file name; “-t” to specify render effect; “-b” to specify brightness, and the default is to make the image fullscreen, with the UI being hide?

**Comment by 13thsymphony** [comment]
@tommywei-cpu, thanks for the suggestion!

Looks like we can add command line activation via:
https://blogs.windows.com/windowsdeveloper/2017/07/05/command-line-activation-universal-windows-apps/#5YJUzjBoXCL4MhAe.97

But I'm not sure whether a UWP app can access arbitrary files, i.e. the UWP sandbox normally requires opening UI (the file picker), or manifesting for the restricted broadFileSystemAccesss capability which requires approval:
https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions

But, the command line option might also provide access to files within the invoked path:
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp#uwp-console-app-behavior

An alternative is to register the viewer as the default file format handler for the file type you are interested in, and then invoke the file in a command prompt. That will launch the app. I can add persistent settings in the UI equivalent to -f -t -b. Would that work or do you need explicit invocation ability?

**Comment by tommywei-cpu** [comment]
@13thsymphony Hey Simon, thanks for the reply. Register the viewer as the default seems a good idea, as long as the UI can be hidden with the images being shown full screen. Persistent setting will be OK. I can implement different -t and -b when producing images. For render effect, "no effect" as a default is OK.

**Comment by 13thsymphony** [comment]
@tommywei-cpu, I have a new version that supports command line invocation, version 1.0.6.0. It should be published to the store shortly.
