### ISSUE TITLE
[CSApp] file format registration for HEIC and AVIF

### ISSUE THREAD

**Issue by 13thsymphony** [13thsymphony/HDRImageViewer#33]
Needs to be robust to RS5 and below.

**Comment by 13thsymphony** [comment]
Fixed by a55c6c64.

**Comment by ValZapod** [comment]
So that means PQ in AVIF is supported?

**Comment by 13thsymphony** [comment]
Yes, AV1 and HEVC1 BT.2100 PQ is supported, assuming that the image container is compliant with the MIAF standard. There was basically no publicly available native BT.2100 PQ content available at the time I added this support, so I didn't have a chance to do much testing.
