### ISSUE TITLE
Command line for tone mapping option

### ISSUE THREAD

**Issue by tommywei-cpu** [13thsymphony/HDRImageViewer#41]
@13thsymphony is it possible to add another  input for command line, which allows switching between the tone mapping option? Thank you for the help!

**Comment by 13thsymphony** [comment]
Sorry, I haven't had time to do much feature work on recently. This is definitely doable and I will add it in the next version, thanks for the suggestion.

**Comment by tommywei-cpu** [comment]
@13thsymphony any chance to add this feature? thanks

**Comment by 13thsymphony** [comment]
Very belated response, this is now done in #57.
