### ISSUE TITLE
Elevated black level is shown for content with color profile

### ISSUE THREAD

**Issue by daspr-Microsoft** [13thsymphony/HDRImageViewer#43]
When showing content with a color profile, the black level is elevated beyond where it should be.

**Comment by ValZapod** [comment]
Actually in that case the black point is defined so it is color managed and black is not black of 0.0001 nits. Yeah.

**Comment by 13thsymphony** [comment]
Possibly fixed with 899c538b846e0b057430da91e925e2cfa1344584.
