### ISSUE TITLE
Unable to display HDR picture at full 6K resoultion

### ISSUE THREAD

**Issue by imbushuo** [13thsymphony/HDRImageViewer#48]
So I have a Pro Display XDR, using this app to open a picture at full screen of 4K resolution works, but 6K prompts file corruption.

Might correlated to https://github.com/13thsymphony/HDRImageViewer/issues/47

**Comment by imbushuo** [comment]
So I think it died while calculating the histogram data for HDR content, complaining intermediate tile being too large in the histogram effect. 🤔

**Comment by imbushuo** [comment]
A possible fix at https://github.com/13thsymphony/HDRImageViewer/pull/49

**Comment by Sawtaytoes** [comment]
Could you upload the image? I'd like to see if it's fixed now that these PRs are merged.

**Comment by 13thsymphony** [comment]
For reference, an example repro image is [here from #47](https://github.com/13thsymphony/HDRImageViewer/files/7989701/Red.Dead.Redemption.2.18_01_2022.02_02_14.zip).

Believed fixed with #49, although I was not able to repro the issue on my setup.
